### ISSUE TITLE
Support for nested claim names

### ISSUE THREAD

**Issue by col-panic** [kjdev/nginx-auth-jwt#12]
You define that 

`claim_name` - should be a name of jwt claim. (sub,roles,scope)

now Keycloak by default delivers realm roles like this

```
  "realm_access": {
    "roles": [
      "rdus-admin",
      "offline_access",
      "default-roles-medelexis",
      "uma_authorization"
    ]
  }
```

so I expected this to work

```
auth_jwt_require_claim realm_access.roles intersect $required_jwt_roles; 
```

which, however, not seems to be the case as the log says `auth_jwt: rejected due to missing claim: realm_access.roles while sending to client`.

Is my parameter wrong for `claim_name` wrong, or does the plugin not support nested claims like this?

Thanks a lot for your work!!!

**Comment by kjdev** [comment]
Introduced a directive auth_jwt allow nested to support nested claims/headers in JWT tokens.

See: [README](https://github.com/kjdev/nginx-auth-jwt?tab=readme-ov-file#auth_jwt_allow_nested)

**Comment by col-panic** [comment]
When do you plan a next release, such that it becomes included in alpine linux? Current is based on 0.6.0 https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx-mod-http-auth-jwt

**Comment by kjdev** [comment]
Create a new version and make sure the Alpine package is updated.

**Comment by kjdev** [comment]
Updated to 0.7.0.

https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx-mod-http-auth-jwt
